### ISSUE TITLE
Datasets preprocessing

### ISSUE THREAD

**Issue by Kavato** [cd-wang/RAIDS#1]
Hello!
What program did you process h5 format datasets and create csv from them? Like for example comma.ai.
If it’s not difficult for you, you can add the program or code that you used to process the data.
Thank you so much.

**Comment by cd-wang** [comment]
Hi Kavato.

A file named "data_extract-commaiai.py" has been added under the folder ./RAIDS/commaai_data_try/. Please take a look.
